# Generated by Django 5.2.10 on 2026-01-18 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accounts",
            options={"verbose_name": "Account", "verbose_name_plural": "Accounts"},
        ),
    ]
