# Generated by Django 5.2.10 on 2026-03-05 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_alter_cart_cart_id_alter_cart_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartitem",
            options={"ordering": ["id"]},
        ),
    ]
